require('options')
require('plugins')
require('colorcheme-config')
require('nvim-treesiter-config')
require('lualine-config')
require('bufferline-config')
require('nvim-tree-config')
require('keymapping')
